import { forwardRef } from "react";
import type { Nutrition } from "../types";
import { NutritionLabelPrint } from "./NutritionLabelPrint";
import { font } from "../data/brand";

interface Props {
  recipeName: string;
  servingSize: string;
  nutrition: Nutrition;
}

/** Printable wrapper: recipe name header + FDA nutrition label (all inline styles) */
export const PrintableNutritionFacts = forwardRef<HTMLDivElement, Props>(
  ({ recipeName, servingSize, nutrition }, ref) => (
    <div
      ref={ref}
      style={{
        fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
        color: "#000",
        padding: 0,
        backgroundColor: "#fff",
      }}
    >
      {/* Recipe name header */}
      <div
        style={{
          marginBottom: 16,
          borderBottom: "2px solid #000",
          paddingBottom: 8,
        }}
      >
        <div
          style={{
            fontSize: 24,
            fontWeight: 800,
            fontFamily: font.header,
          }}
        >
          {recipeName || "Untitled Recipe"}
        </div>
        <div style={{ fontSize: 13, color: "#555", marginTop: 4 }}>
          Serving Size: {servingSize}
        </div>
      </div>

      {/* FDA nutrition label */}
      <NutritionLabelPrint nutrition={nutrition} servingSize={servingSize} />

      {/* Footer */}
      <div
        style={{
          marginTop: 24,
          paddingTop: 8,
          borderTop: "1px solid #ddd",
          fontSize: 11,
          color: "#999",
          textAlign: "center",
        }}
      >
        Generated by SproutCNP — School Nutrition & Compliance Tool
      </div>
    </div>
  ),
);
